TicketingWebApp/Pages/CreateTicket.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;
using TicketingWebApp.Model;

namespace TicketingWebApp.Pages
{
    [Authorize]
    public class CreateTicketModel : PageModel
    {
        [BindProperty]
        public Ticket Model { get; set; }

        TicketDbContext ticketDbContext;
        UserManager<IdentityUser> userManager;

        public CreateTicketModel(TicketDbContext ticketDbContext, UserManager<IdentityUser> userManager)
        {
            this.ticketDbContext = ticketDbContext;
            this.userManager = userManager;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                Model.CreatedByUserId = userManager.GetUserId(User);
                ticketDbContext.Tickets.Add(this.Model);
                // Log event
                await ticketDbContext.SaveChangesAsync();
                ticketDbContext.LogEvents.Add(new LogEvent() { Type = "Ticket Created", Description = $"Id:{Model.Id};Title:{Model.Title};Description:{Model.Description};" });
                await ticketDbContext.SaveChangesAsync();
                return RedirectToPage("ViewTickets");
            }
            return Page();
        }
    }
}

TicketingWebApp/Pages/DeleteTicket.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TicketingWebApp.Model;

namespace TicketingWebApp.Pages
{
    [Authorize]
    public class DeleteTicketModel : PageModel
    {
        private readonly TicketingWebApp.Model.TicketDbContext _context;
        private UserManager<IdentityUser> userManager;


        public DeleteTicketModel(TicketingWebApp.Model.TicketDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            this.userManager = userManager;
        }

        [BindProperty]
        public Ticket Ticket { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // Check if authorized
            var tempTicket = await _context.Tickets.FirstOrDefaultAsync(m => m.Id == id);
            if (tempTicket == null)
            {
                return NotFound();
            }
            if (userManager.GetUserName(User) == "admin")
            {
                Ticket = await _context.Tickets.FirstOrDefaultAsync(m => m.Id == id);
            }

            if (Ticket == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // Check if authorized
            var tempTicket = await _context.Tickets.FirstOrDefaultAsync(m => m.Id == id);
            if (tempTicket == null)
            {
                return NotFound();
            }
            if (userManager.GetUserName(User) == "admin")
            {
                Ticket = await _context.Tickets.FindAsync(id);
            }

            if (Ticket != null)
            {
                _context.Tickets.Remove(Ticket);
                _context.TicketComments.RemoveRange(_context.TicketComments.Where(c => c.TicketId == Ticket.Id));
                // Log event
                _context.LogEvents.Add(new LogEvent() { Type = "Ticket Deleted", Description = $"Id:{id};" });
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./ViewTickets");
        }
    }
}

TicketingWebApp/Pages/EditTicket.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TicketingWebApp.Model;

namespace TicketingWebApp.Pages
{
    [Authorize]
    public class EditTicketModel : PageModel
    {
        private readonly TicketingWebApp.Model.TicketDbContext _context;
        private UserManager<IdentityUser> userManager;

        public EditTicketModel(TicketingWebApp.Model.TicketDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            this.userManager = userManager;
        }

        [BindProperty]
        public Ticket Ticket { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // Check if authorized
            var tempTicket = await _context.Tickets.FirstOrDefaultAsync(m => m.Id == id);
            if (tempTicket == null)
            {
                return NotFound();
            }
            if (userManager.GetUserName(User) == "admin" || userManager.GetUserId(User) == tempTicket.CreatedByUserId)
            {
                Ticket = await _context.Tickets.FirstOrDefaultAsync(m => m.Id == id);
            }

            if (Ticket == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            // Check if authorized
            var tempTicket = await _context.Tickets.FirstOrDefaultAsync(m => m.Id == Ticket.Id);
            if (tempTicket == null)
            {
                return NotFound();
            }
            if (userManager.GetUserName(User) == "admin" || userManager.GetUserId(User) == tempTicket.CreatedByUserId)
            {
                //Log Event
                _context.LogEvents.Add(new LogEvent() { Type = "Ticket Updated", Description = $"Id:{Ticket.Id} Title:{Ticket.Title};Description:{Ticket.Description};" });
                //Update
                _context.ChangeTracker.Clear();
                _context.Attach(Ticket).State = EntityState.Modified;
            }
            else
            {
                return NotFound();
            }

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)

            {
                if (!TicketExists(Ticket.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            //return RedirectToPage("./ViewTickets");
            return RedirectToPage("./Ticket/", new { id = Ticket.Id });
        }

        private bool TicketExists(int id)
        {
            return _context.Tickets.Any(e => e.Id == id);
        }
    }
}

TicketingWebApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace TicketingWebApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

TicketingWebApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TicketingWebApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

TicketingWebApp/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;
using TicketingWebApp.Model;
using TicketingWebApp.ViewModel;

namespace TicketingWebApp.Pages
{
    public class LoginModel : PageModel
    {
        [BindProperty]
        public Login Model { get; set; }


        private readonly SignInManager<IdentityUser> signInManager;
        private readonly TicketDbContext ticketDbContext;

        public LoginModel(SignInManager<IdentityUser> signInManager, TicketDbContext ticketDbContext)
        {
            this.signInManager = signInManager;
            this.ticketDbContext = ticketDbContext;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            if (ModelState.IsValid)
            {
                var identityResult = await signInManager.PasswordSignInAsync(Model.Username, Model.Password, Model.RememberMe, true);
                if (identityResult.Succeeded)
                {
                    // Log event
                    ticketDbContext.LogEvents.Add(new LogEvent() { Type = "Login Success", Description = $"Username:{Model.Username};" });
                    await ticketDbContext.SaveChangesAsync();

                    if (returnUrl == null || returnUrl == "/")
                    {
                        return RedirectToPage("Index");
                    }
                    else
                    {
                        return RedirectToPage(returnUrl);
                    }
                }
                else
                {
                    // Log event
                    ticketDbContext.LogEvents.Add(new LogEvent() { Type = "Login Failed", Description = $"Username:{Model.Username};" });
                    await ticketDbContext.SaveChangesAsync();
                }

                ModelState.AddModelError("", "Username or Password incorrect");
            }

            return Page();
        }
    }
}

TicketingWebApp/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;
using TicketingWebApp.Model;

namespace TicketingWebApp.Pages
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<IdentityUser> signInManager;
        private UserManager<IdentityUser> userManager;
        private TicketDbContext ticketDbContext;

        public LogoutModel(SignInManager<IdentityUser> signInManager, TicketDbContext ticketDbContext, UserManager<IdentityUser> userManager)
        {
            this.signInManager = signInManager;
            this.userManager = userManager;
            this.ticketDbContext = ticketDbContext;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostLogoutAsync()
        {
            // Log event
            ticketDbContext.LogEvents.Add(new LogEvent() { Type = "Logout", Description = $"Username:{userManager.GetUserName(User)};" });
            await ticketDbContext.SaveChangesAsync();
            // Sign out
            await signInManager.SignOutAsync();
            return RedirectToPage("Login");
        }

        public IActionResult OnPostDontLogoutAsync()
        {
            return RedirectToPage("Index");
        }
    }
}

TicketingWebApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TicketingWebApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

TicketingWebApp/Pages/Register.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;
using TicketingWebApp.ViewModel;

namespace TicketingWebApp.Pages
{
    public class RegisterModel : PageModel
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;
        private readonly RoleManager<IdentityRole> roleManager;

        [BindProperty]
        public Register Model { get; set; }
        
        public RegisterModel(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, RoleManager<IdentityRole> roleManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.roleManager = roleManager;
        }
        
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var user = new IdentityUser()
                {
                    Email = Model.Email,
                    UserName = Model.Username,
                };

                var result = await userManager.CreateAsync(user, Model.Password);
                if (result.Succeeded)
                {
                    //await userManager.AddToRoleAsync(user, Enums)
                    await signInManager.SignInAsync(user, false);
                    return RedirectToPage("Index");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }

            return Page();
        }
    }
}

TicketingWebApp/Pages/TicketUnsafe.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TicketingWebApp.Model;

namespace TicketingWebApp.Pages
{
    [Authorize]
    public class TicketUnsafeModel : PageModel
    {
        private readonly TicketingWebApp.Model.TicketDbContext _context;
        private UserManager<IdentityUser> userManager;


        public TicketUnsafeModel(TicketingWebApp.Model.TicketDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            this.userManager = userManager;
        }

        public Ticket Ticket { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // Check if authorized
            var tempTicket = await _context.Tickets.FirstOrDefaultAsync(m => m.Id == id);
            if (tempTicket == null)
            {
                return NotFound();
            }
            if (userManager.GetUserName(User) == "admin" || userManager.GetUserId(User) == tempTicket.CreatedByUserId)
            {
                Ticket = await _context.Tickets.FirstOrDefaultAsync(m => m.Id == id);
            }

            if (Ticket == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

TicketingWebApp/Pages/ViewTickets.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TicketingWebApp.Model;

namespace TicketingWebApp.Pages
{
    [Authorize]
    public class ViewTicketsModel : PageModel
    {
        public IEnumerable<Ticket> tickets;
        private TicketDbContext _ticketDbContext;
        private UserManager<IdentityUser> userManager;

        public ViewTicketsModel(TicketDbContext ticketDbContext, UserManager<IdentityUser> userManager)
        {
            _ticketDbContext = ticketDbContext;
            this.userManager = userManager;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            if (userManager.GetUserName(User) == "admin")
            {
                tickets = _ticketDbContext.Tickets;
            }
            else
            {
                tickets = _ticketDbContext.Tickets.Where(t => t.CreatedByUserId == userManager.GetUserId(User));
            }
            
            // Fill in user names
            foreach (var ticket in tickets)
            {
                var user = await userManager.FindByIdAsync(ticket.CreatedByUserId);
                ticket.CreatedByUserName = user.UserName;

                ticket.TicketComments = _ticketDbContext.TicketComments.Where(c => c.TicketId == ticket.Id).ToList();
            }

            return Page();
        }
    }
}

TicketingWebApp/Pages/CreateTicket.cshtml
@page
@model TicketingWebApp.Pages.CreateTicketModel
@{
}
<h1>Create Ticket</h1>
<form method="post">
        <div class="mb-3">
            <label class="form-label" asp-for="Model.Title">Title</label>
            <input type="text" asp-for="Model.Title" class="form-control" />
            <span asp-validation-for="Model.Title" class="text-danger"></span>
        </div>
        <div class=mb-3>
            <label class="form-label" asp-for="Model.Description">Description</label>
            <textarea type="text" asp-for="Model.Description" class="form-control">
            </textarea>
            <span asp-validation-for="Model.Description" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
</form>

TicketingWebApp/Pages/DeleteTicket.cshtml
@page
@model TicketingWebApp.Pages.DeleteTicketModel

@{
    ViewData["Title"] = "DeleteTicket";
}

<h1>Delete Ticket</h1>

<h3>Are you sure you want to delete this Ticket?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ticket.CreatedByUserId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ticket.CreatedByUserId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ticket.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ticket.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ticket.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ticket.Description)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Ticket.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./ViewTickets">Back to List</a>
    </form>
</div>

TicketingWebApp/Pages/EditTicket.cshtml
@page
@model TicketingWebApp.Pages.EditTicketModel

@{
    ViewData["Title"] = "EditTicket";
}

<h1>Edit Ticket</h1>
<div class="row">
    <div>
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Ticket.Id" />
            <div class="form-group mb-3">
                @*<label asp-for="Ticket.CreatedByUserId" class="control-label"></label>*@
                <input asp-for="Ticket.CreatedByUserId" class="form-control" readonly hidden/>
                @*<span asp-validation-for="Ticket.CreatedByUserId" class="text-danger"></span>*@
            </div>
            <div class="form-group mb-3">
                <label asp-for="Ticket.Title" class="control-label"></label>
                <input asp-for="Ticket.Title" class="form-control" />
                <span asp-validation-for="Ticket.Title" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Ticket.Description" class="control-label"></label>
                <textarea asp-for="Ticket.Description" class="form-control"></textarea>
                <span asp-validation-for="Ticket.Description" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <input type="submit" value="Save" class="btn btn-primary btn-space" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./ViewTickets">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TicketingWebApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    @if (signInManager.IsSignedIn(User))
    {
        <p>Welcome to my ticket tracking web application, feel free to <a asp-page="/CreateTicket">create a new ticket</a></p>
    }
    else
    {
        <p>Welcome to my ticket tracking web application, please <a asp-page="/Login">login</a> to continue</p>
    }
    <p>Created by Kyle Hamilton</p>
</div>

TicketingWebApp/Pages/Login.cshtml
@page
@model TicketingWebApp.Pages.LoginModel
@{
}

<div class="container mt-5">
    <div class="row justify-content-center alignalign-items-center">
        <div class="col-sm-12 col-md-12 col-lg-4">
            <h1 class="mb-3">Login</h1>

            <form method="post">
                <div class="mb-3">
                    <label class="form-label" asp-for="Model.Username">Username</label>
                    <input type="text" asp-for="Model.Username" class="form-control"/>
                    <span asp-validation-for="Model.Username" class="text-danger"></span>
                </div>
                <div class=mb-3>
                    <label class="form-label" asp-for="Model.Password">Password</label>
                    <input type="password" asp-for="Model.Password" class="form-control" />
                    <span asp-validation-for="Model.Password" class="text-danger"></span>
                </div>
                <div class="mb-3 form-check">
                    <input type="checkbox" asp-for="Model.RememberMe" class="form-check-input" />
                    <label class="form-check-label" asp-for="Model.RememberMe">Remember Me?</label>
                </div>
                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>
            </form>
        </div>
    </div>
</div>

TicketingWebApp/Pages/Logout.cshtml
@page
@model TicketingWebApp.Pages.LogoutModel
@{
}

<form method="post">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-12 col-lg-4">
                <p>Are you sure you want to logout?</p>
                <p>
                    <button class="btn btn-primary" asp-page-handler="Logout">Yes</button>
                    <button class="btn btn-light ml-5 border-dark" asp-page-handler="DontLogout">No</button>
                </p>
            </div>
        </div>
    </div>
</form>

TicketingWebApp/Pages/Register.cshtml
@page
@model TicketingWebApp.Pages.RegisterModel
@{
}

<div class="container mt-5">
    <div class="row align-content-center align-items-center">
        <div class="col-sm-12 col-md-12 col-lg-4">
            <h1 class="mb-3">Register</h1>

            <form method="post">
                <div asp-validation-summary="All" class="text-danger">
                </div>
                <div class="mb-3">
                    <label class="form-label" asp-for="Model.Email">Email Address</label>
                    <Input type="text" asp-for="Model.Email" class="form-control" />
                    <span asp-validation-for="Model.Email" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label class="form-label" asp-for="Model.Username">Username</label>
                    <Input type="text" asp-for="Model.Username" class="form-control" />
                    <span asp-validation-for="Model.Username" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label class="form-label" asp-for="Model.Password">Password</label>
                    <Input type="password" asp-for="Model.Password" class="form-control" />
                    <span asp-validation-for="Model.Password" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label class="form-label" asp-for="Model.ConfirmPassword">Confirm Password</label>
                    <Input type="password" asp-for="Model.ConfirmPassword" class="form-control" />
                    <span asp-validation-for="Model.ConfirmPassword" class="text-danger"></span>
                </div>
                <div class="mb3">
                    <button type="submit" class="btn alert-primary">Register</button>
                </div>
            </form>
        </div>
    </div>
</div>

TicketingWebApp/Pages/Ticket.cshtml
@page
@model TicketingWebApp.Pages.TicketModel

@{
    ViewData["Title"] = "Ticket";
}

<div>
    <h1>Ticket</h1>
    <a class="btn btn-danger btn-space" asp-page="/TicketUnsafe" asp-route-id="@Model.Ticket.Id">View Unsafe</a>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ticket.CreatedByUserName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ticket.CreatedByUserName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ticket.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ticket.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ticket.Description)
        </dt>
        <dd class="col-sm-10" style="word-wrap: break-word">
            @Html.Raw(Html.Encode(Model.Ticket.Description))
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./EditTicket" asp-route-id="@Model.Ticket.Id">Edit</a> |
    <a asp-page="./ViewTickets">Back to List</a>
</div>
<hr />
<div class=mb-3>
    <h3>Comments</h3>
    @if (Model.TicketComments.Count() == 0)
    {
        <p>No comments yet</p>
    }
    else
    {
        <table>
            <thead>
                <tr>
                    <th>
                        User
                    </th>
                    <th>
                        Comment
                    </th>
                    <th>
                        Date
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var comment in Model.TicketComments)
                {
                    <tr>
                        <td width="20%">@comment.CreatedByUserName</td>
                        <td width="60%">@comment.Text</td>
                        <td width="20%">@comment.CreatedDateTime</td>
                    </tr>
                }
            </tbody>
        </table>
    }
    @*<label class="form-label" asp-for="Model.Description">Description</label>
        <textarea type="text" asp-for="Model.Description" class="form-control">
        </textarea>
        <span asp-validation-for="Model.Description" class="text-danger"></span>*@
    <hr />
    <h5>Post Comment</h5>
    <form method="post">
        <div class="mb-3">
            <input type="text" asp-for="Model.TicketId" value="@Model.Ticket.Id" readonly hidden>
            <textarea width type="text" asp-for="Model.Text" class="form-control"></textarea>
            <span asp-validation-for="Model.Text" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-outline-primary btn-space">Post</button>
        </div>
    </form>
</div>

TicketingWebApp/Pages/TicketUnsafe.cshtml
@page
@model TicketingWebApp.Pages.TicketUnsafeModel

@{
    ViewData["Title"] = "TicketUnsafe";
}

<div>
    <h1>Ticket</h1>
    <div class="p-3 mb-2 bg-danger text-white">Unsafe</div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ticket.CreatedByUserId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ticket.CreatedByUserId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ticket.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ticket.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ticket.Description)
        </dt>
        <dd class="col-sm-10" style="word-wrap: break-word">
            @Html.Raw(@Model.Ticket.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./ViewTickets">Back to List</a>
</div>